# Generated by Django 6.1.1 on 2026-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фотография')),
                ('intro', models.TextField(default='Здравствуйте! Меня зовут ... и я расскажу немного о себе.', verbose_name='Вступительный текст')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('philosophy', models.TextField(blank=True, verbose_name='Педагогическое кредо / принципы преподавания')),
                ('achievements_summary', models.TextField(blank=True, verbose_name='Краткая информация о наградах и достижениях')),
                ('hobbies', models.TextField(blank=True, verbose_name='Увлечения и интересы')),
            ],
            options={
                'verbose_name': 'Страница «Обо мне»',
                'verbose_name_plural': 'Страница «Обо мне»',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотогалерея',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MethodicalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('lesson', 'Разработка урока'), ('event', 'Внеклассное мероприятие'), ('presentation', 'Презентация'), ('article', 'Статья / публикация'), ('other', 'Другое')], default='lesson', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Класс / параллель')),
                ('file', models.FileField(blank=True, null=True, upload_to='methodical/files/', verbose_name='Файл материала')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='methodical/covers/', verbose_name='Изображение-обложка')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Методический материал',
                'verbose_name_plural': 'Методическая копилка',
                'ordering': ['order', '-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Портфолио', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, default='В этом разделе собраны материалы, отражающие мою педагогическую деятельность.', verbose_name='Вводный текст раздела')),
            ],
            options={
                'verbose_name': 'Страница «Портфолио»',
                'verbose_name_plural': 'Страница «Портфолио»',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Портфолио учителя', max_length=200, verbose_name='Название сайта')),
                ('teacher_full_name', models.CharField(default='Иванова Мария Петровна', max_length=200, verbose_name='ФИО учителя')),
                ('teacher_position', models.CharField(default='Учитель русского языка и литературы', max_length=255, verbose_name='Должность / предмет')),
                ('logo_initials', models.CharField(blank=True, default='МП', max_length=5, verbose_name='Инициалы для логотипа')),
                ('hero_title', models.CharField(default='Добро пожаловать на мой сайт-портфолио', max_length=255, verbose_name='Заголовок на главной странице')),
                ('hero_subtitle', models.TextField(default='Учитель русского языка и литературы высшей категории', verbose_name='Подзаголовок на главной странице')),
                ('hero_photo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фото для главной страницы')),
                ('hero_quote', models.TextField(blank=True, default='«Слово — дело великое. Великое потому, что словом можно соединить людей, словом можно и разъединить их, словом можно служить любви, словом же можно служить вражде и ненависти» — Л.Н. Толстой', verbose_name='Цитата на главной странице')),
                ('about_preview', models.TextField(blank=True, default='Расскажите немного о себе — этот текст будет показан на главной странице.', verbose_name='Краткое описание для блока «Обо мне» на главной')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Место работы / адрес')),
                ('vk_url', models.URLField(blank=True, verbose_name='Ссылка ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Ссылка Telegram')),
                ('footer_text', models.CharField(blank=True, default='Сайт-портфолио учителя русского языка и литературы', max_length=255, verbose_name='Текст в подвале сайта')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('student_name', models.CharField(blank=True, max_length=255, verbose_name='Имя учащегося')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='achievements/students/', verbose_name='Изображение (скан грамоты и т.п.)')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Достижение учащегося',
                'verbose_name_plural': 'Достижения учащихся',
                'ordering': ['order', '-year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='achievements/teacher/', verbose_name='Изображение (скан грамоты и т.п.)')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Моё достижение',
                'verbose_name_plural': 'Мои достижения',
                'ordering': ['order', '-year', '-id'],
            },
        ),
    ]
