# Generated by Django 6.1.1 on 2026-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherachievement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='achievements/teacher/files/', verbose_name='Файл (полный текст, документ)'),
        ),
        migrations.AlterField(
            model_name='teacherachievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/teacher/', verbose_name='Изображение (скан грамоты и т.п.)'),
        ),
    ]
